FROM golang:1.24 AS builder

WORKDIR /app

COPY go.mod go.sum ./
RUN go mod download

COPY . .

RUN CGO_ENABLED=0 GOOS=linux go build -a -tags netgo -ldflags '-w -s' -o myapp ./cmd/api/main.go

FROM alpine:latest
WORKDIR /root/
COPY --from=builder /app/myapp .

CMD ["./myapp"]