env: "local"

http_server:
  address: "localhost:8080"
  read_timeout: "4s"
  idle_timeout: "60s"
  context_timeout: "10s"

tarantool:
  host: "0.0.0.0:3301"
  user: "user"
  password: "password"
  timeout: "1m"
  